// Setup wizard — creates the rsvps table automatically or guides the user
import { createClient } from '@supabase/supabase-js'

const TABLE_SQL = `CREATE TABLE IF NOT EXISTS rsvps (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  attending TEXT NOT NULL CHECK (attending IN ('yes', 'no')),
  submitted_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_rsvps_submitted_at ON rsvps(submitted_at DESC);`

function getEnv() {
  const url = process.env.SUPABASE_URL || ''
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY || ''
  return { url, key, configured: !!(url && key && !url.startsWith('your-')) }
}

function projectRef(url) {
  try {
    const host = new URL(url).hostname // e.g. abcdef.supabase.co
    return host.split('.')[0]
  } catch {
    // Invalid URL is expected when user hasn't configured env vars yet
    return null
  }
}

async function tableExists(supabase) {
  const { error } = await supabase.from('rsvps').select('id').limit(1)
  if (!error) return true
  if (error.message && error.message.includes('does not exist')) return false
  if (error.code === '42P01') return false          // relation does not exist
  if (error.code === 'PGRST204') return false        // no such table
  // Some other error (permissions, network, etc) — assume table may exist
  return null
}

export default async function handler(req, res) {
  res.setHeader('Content-Type', 'text/html; charset=utf-8')

  const env = getEnv()
  const ref = env.configured ? projectRef(env.url) : null

  let tableStatus = null // null = unknown, true = exists, false = missing
  let tableError = null

  if (env.configured) {
    try {
      const supabase = createClient(env.url, env.key)
      tableStatus = await tableExists(supabase)
    } catch (e) {
      tableError = e.message
    }
  }

  const sqlEditorLink = ref
    ? `https://supabase.com/dashboard/project/${ref}/sql/new`
    : 'https://supabase.com/dashboard'

  const tableEditorLink = ref
    ? `https://supabase.com/dashboard/project/${ref}/editor`
    : 'https://supabase.com/dashboard'

  const settingsLink = ref
    ? `https://supabase.com/dashboard/project/${ref}/settings/api`
    : 'https://supabase.com/dashboard'

  const envDone = env.configured
  const tableDone = tableStatus === true

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>RSVP Setup Wizard</title>
  <style>
    *{box-sizing:border-box;margin:0;padding:0}
    body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;background:#faf9f7;color:#1a1a2e;line-height:1.6;padding:2rem 1rem}
    .container{max-width:680px;margin:0 auto}
    h1{font-size:1.8rem;text-align:center;margin-bottom:.25rem;color:#8B4465}
    .subtitle{text-align:center;color:#666;margin-bottom:2rem;font-size:.95rem}
    .step{background:#fff;border:1px solid #e5e5e5;border-radius:12px;padding:1.5rem;margin-bottom:1.25rem;position:relative}
    .step.done{border-color:#22c55e;background:#f0fdf4}
    .step.action{border-color:#f59e0b;background:#fffbeb}
    .step.error{border-color:#ef4444;background:#fef2f2}
    .step-header{display:flex;align-items:center;gap:.75rem;margin-bottom:.75rem}
    .badge{width:32px;height:32px;border-radius:50%;display:flex;align-items:center;justify-content:center;font-weight:700;font-size:.9rem;color:#fff;flex-shrink:0}
    .badge.green{background:#22c55e}
    .badge.amber{background:#f59e0b}
    .badge.red{background:#ef4444}
    .badge.gray{background:#9ca3af}
    .step-title{font-weight:600;font-size:1.05rem}
    .step p{color:#555;font-size:.92rem;margin-bottom:.5rem}
    .btn{display:inline-block;padding:.65rem 1.25rem;border-radius:8px;font-size:.9rem;font-weight:600;text-decoration:none;cursor:pointer;border:none;transition:all .15s}
    .btn-primary{background:#8B4465;color:#fff}
    .btn-primary:hover{background:#6d3550}
    .btn-outline{background:#fff;color:#8B4465;border:2px solid #8B4465}
    .btn-outline:hover{background:#fdf2f8}
    .btn-green{background:#22c55e;color:#fff}
    .btn-green:hover{background:#16a34a}
    .sql-box{background:#1e1e2e;color:#a6e3a1;padding:1rem;border-radius:8px;font-family:"Fira Code",monospace;font-size:.8rem;overflow-x:auto;white-space:pre-wrap;margin:.75rem 0;position:relative;line-height:1.5}
    .copy-btn{position:absolute;top:.5rem;right:.5rem;background:#8B4465;color:#fff;border:none;padding:.35rem .75rem;border-radius:6px;font-size:.75rem;cursor:pointer}
    .copy-btn:hover{background:#6d3550}
    .actions{display:flex;gap:.75rem;flex-wrap:wrap;margin-top:1rem}
    .instructions{background:#f8f7ff;border:1px solid #e0dff5;border-radius:8px;padding:1rem;margin:.75rem 0}
    .instructions ol{padding-left:1.25rem}
    .instructions li{margin-bottom:.5rem;font-size:.9rem}
    .check{color:#22c55e;font-weight:700}
    .cross{color:#ef4444;font-weight:700}
    .all-done{text-align:center;padding:2rem;background:#f0fdf4;border:2px solid #22c55e;border-radius:12px;margin-top:1.5rem}
    .all-done h2{color:#22c55e;margin-bottom:.5rem}
    .all-done p{color:#555}
    .all-done a{color:#8B4465;font-weight:600}
  </style>
</head>
<body>
  <div class="container">
    <h1>🎉 RSVP Setup Wizard</h1>
    <p class="subtitle">Let's get your RSVP database working — just follow the steps below.</p>

    <!-- STEP 1: Environment Variables -->
    <div class="step ${envDone ? 'done' : 'action'}">
      <div class="step-header">
        <div class="badge ${envDone ? 'green' : 'amber'}">${envDone ? '✓' : '1'}</div>
        <div class="step-title">${envDone ? 'Environment variables are set ✓' : 'Set your Supabase environment variables'}</div>
      </div>
      ${envDone ? '<p>Connected to Supabase project: <strong>' + ref + '</strong></p>' : `
      <p>You need to add two values from your Supabase project to Vercel.</p>
      <div class="instructions">
        <ol>
          <li>Open your <a href="${settingsLink}" target="_blank"><strong>Supabase project → Settings → API</strong></a></li>
          <li>Copy the <strong>Project URL</strong> (looks like <code>https://abc123.supabase.co</code>)</li>
          <li>Copy the <strong>service_role</strong> secret key (starts with <code>eyJ…</code>)</li>
          <li>Go to your <strong>Vercel project → Settings → Environment Variables</strong></li>
          <li>Add: <code>SUPABASE_URL</code> = your Project URL</li>
          <li>Add: <code>SUPABASE_SERVICE_ROLE_KEY</code> = your service_role key</li>
          <li><strong>Redeploy</strong> your Vercel project (Deployments → ⋮ → Redeploy)</li>
        </ol>
      </div>
      `}
    </div>

    <!-- STEP 2: Create Table -->
    <div class="step ${tableDone ? 'done' : (envDone ? 'action' : '')} ${tableError ? 'error' : ''}">
      <div class="step-header">
        <div class="badge ${tableDone ? 'green' : (envDone ? 'amber' : 'gray')}">${tableDone ? '✓' : '2'}</div>
        <div class="step-title">${tableDone ? 'Database table exists ✓' : 'Create the RSVP table'}</div>
      </div>
      ${tableDone ? '<p>The <strong>rsvps</strong> table is ready to store data.</p>' : (tableError ? '<p class="cross">Connection error: ' + tableError + '</p>' : (envDone ? `
      <p>Your Supabase project is connected, but the <strong>rsvps</strong> table hasn't been created yet. Here's how to create it in 3 clicks:</p>
      <div class="instructions">
        <ol>
          <li>Click the button below to open your Supabase <strong>SQL Editor</strong></li>
          <li>Click <strong>"Copy SQL"</strong> to copy the table code, then <strong>paste</strong> it into the editor</li>
          <li>Click the green <strong>"Run"</strong> button (or press Ctrl+Enter)</li>
        </ol>
      </div>
      <div style="position:relative">
        <div class="sql-box" id="sql-code">${TABLE_SQL}</div>
        <button class="copy-btn" onclick="copySQL()">📋 Copy SQL</button>
      </div>
      <div class="actions">
        <a href="${sqlEditorLink}" target="_blank" class="btn btn-primary">Open SQL Editor →</a>
        <button class="btn btn-outline" onclick="location.reload()">🔄 I've done it — check again</button>
      </div>
      ` : '<p>Complete Step 1 first, then refresh this page.</p>'))}
    </div>

    <!-- STEP 3: All done! -->
    ${envDone && tableDone ? `
    <div class="all-done">
      <h2>🎉 All set!</h2>
      <p>Your RSVP system is fully configured and ready to go.</p>
      <p style="margin-top:1rem">
        <a href="/">← Back to invitation</a> &nbsp;|&nbsp; <a href="/admin">View RSVP Admin →</a>
      </p>
    </div>
    ` : `
    <div class="step">
      <div class="step-header">
        <div class="badge gray">3</div>
        <div class="step-title">You're done!</div>
      </div>
      <p>After completing the steps above, your RSVP form and <a href="/admin">/admin</a> page will work automatically.</p>
    </div>
    `}
  </div>

  <script>
    function copySQL() {
      const sql = document.getElementById('sql-code').textContent
      navigator.clipboard.writeText(sql).then(() => {
        const btn = document.querySelector('.copy-btn')
        btn.textContent = '✅ Copied!'
        setTimeout(() => { btn.textContent = '📋 Copy SQL' }, 2000)
      }).catch(() => {
        // Clipboard API unavailable — select text so user can Ctrl+C
        const range = document.createRange()
        range.selectNodeContents(document.getElementById('sql-code'))
        window.getSelection().removeAllRanges()
        window.getSelection().addRange(range)
        const btn = document.querySelector('.copy-btn')
        btn.textContent = 'Select All — press Ctrl+C'
        setTimeout(() => { btn.textContent = '📋 Copy SQL' }, 3000)
      })
    }
  </script>
</body>
</html>`

  return res.status(200).send(html)
}
